# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install --ignore-scripts

# Copy all source files
COPY . .

# Build the project
RUN npm run build

# Default command to run the built MCP server
CMD ["node", "dist/index.js"]
